
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `orders` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model orders
 * 
 */
export type ordersModel = runtime.Types.Result.DefaultSelection<Prisma.$ordersPayload>

export type AggregateOrders = {
  _count: OrdersCountAggregateOutputType | null
  _avg: OrdersAvgAggregateOutputType | null
  _sum: OrdersSumAggregateOutputType | null
  _min: OrdersMinAggregateOutputType | null
  _max: OrdersMaxAggregateOutputType | null
}

export type OrdersAvgAggregateOutputType = {
  id: number | null
  vehicleId: number | null
  customerId: number | null
  staffId: number | null
}

export type OrdersSumAggregateOutputType = {
  id: number | null
  vehicleId: number | null
  customerId: number | null
  staffId: number | null
}

export type OrdersMinAggregateOutputType = {
  id: number | null
  vehicleId: number | null
  customerId: number | null
  staffId: number | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
  note: string | null
}

export type OrdersMaxAggregateOutputType = {
  id: number | null
  vehicleId: number | null
  customerId: number | null
  staffId: number | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
  note: string | null
}

export type OrdersCountAggregateOutputType = {
  id: number
  vehicleId: number
  customerId: number
  staffId: number
  status: number
  createdAt: number
  updatedAt: number
  note: number
  _all: number
}


export type OrdersAvgAggregateInputType = {
  id?: true
  vehicleId?: true
  customerId?: true
  staffId?: true
}

export type OrdersSumAggregateInputType = {
  id?: true
  vehicleId?: true
  customerId?: true
  staffId?: true
}

export type OrdersMinAggregateInputType = {
  id?: true
  vehicleId?: true
  customerId?: true
  staffId?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  note?: true
}

export type OrdersMaxAggregateInputType = {
  id?: true
  vehicleId?: true
  customerId?: true
  staffId?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  note?: true
}

export type OrdersCountAggregateInputType = {
  id?: true
  vehicleId?: true
  customerId?: true
  staffId?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  note?: true
  _all?: true
}

export type OrdersAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which orders to aggregate.
   */
  where?: Prisma.ordersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders to fetch.
   */
  orderBy?: Prisma.ordersOrderByWithRelationInput | Prisma.ordersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ordersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned orders
  **/
  _count?: true | OrdersCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: OrdersAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: OrdersSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: OrdersMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: OrdersMaxAggregateInputType
}

export type GetOrdersAggregateType<T extends OrdersAggregateArgs> = {
      [P in keyof T & keyof AggregateOrders]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOrders[P]>
    : Prisma.GetScalarType<T[P], AggregateOrders[P]>
}




export type ordersGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ordersWhereInput
  orderBy?: Prisma.ordersOrderByWithAggregationInput | Prisma.ordersOrderByWithAggregationInput[]
  by: Prisma.OrdersScalarFieldEnum[] | Prisma.OrdersScalarFieldEnum
  having?: Prisma.ordersScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OrdersCountAggregateInputType | true
  _avg?: OrdersAvgAggregateInputType
  _sum?: OrdersSumAggregateInputType
  _min?: OrdersMinAggregateInputType
  _max?: OrdersMaxAggregateInputType
}

export type OrdersGroupByOutputType = {
  id: number
  vehicleId: number
  customerId: number
  staffId: number
  status: string
  createdAt: Date
  updatedAt: Date
  note: string | null
  _count: OrdersCountAggregateOutputType | null
  _avg: OrdersAvgAggregateOutputType | null
  _sum: OrdersSumAggregateOutputType | null
  _min: OrdersMinAggregateOutputType | null
  _max: OrdersMaxAggregateOutputType | null
}

export type GetOrdersGroupByPayload<T extends ordersGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OrdersGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OrdersGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OrdersGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OrdersGroupByOutputType[P]>
      }
    >
  >



export type ordersWhereInput = {
  AND?: Prisma.ordersWhereInput | Prisma.ordersWhereInput[]
  OR?: Prisma.ordersWhereInput[]
  NOT?: Prisma.ordersWhereInput | Prisma.ordersWhereInput[]
  id?: Prisma.IntFilter<"orders"> | number
  vehicleId?: Prisma.IntFilter<"orders"> | number
  customerId?: Prisma.IntFilter<"orders"> | number
  staffId?: Prisma.IntFilter<"orders"> | number
  status?: Prisma.StringFilter<"orders"> | string
  createdAt?: Prisma.DateTimeFilter<"orders"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"orders"> | Date | string
  note?: Prisma.StringNullableFilter<"orders"> | string | null
  order_items?: Prisma.Order_itemsListRelationFilter
  customer?: Prisma.XOR<Prisma.CustomersScalarRelationFilter, Prisma.customersWhereInput>
  vehicle?: Prisma.XOR<Prisma.VehiclesScalarRelationFilter, Prisma.vehiclesWhereInput>
  staff?: Prisma.XOR<Prisma.StaffScalarRelationFilter, Prisma.staffWhereInput>
  payements?: Prisma.PaymentsListRelationFilter
}

export type ordersOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  vehicleId?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  order_items?: Prisma.order_itemsOrderByRelationAggregateInput
  customer?: Prisma.customersOrderByWithRelationInput
  vehicle?: Prisma.vehiclesOrderByWithRelationInput
  staff?: Prisma.staffOrderByWithRelationInput
  payements?: Prisma.paymentsOrderByRelationAggregateInput
}

export type ordersWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ordersWhereInput | Prisma.ordersWhereInput[]
  OR?: Prisma.ordersWhereInput[]
  NOT?: Prisma.ordersWhereInput | Prisma.ordersWhereInput[]
  vehicleId?: Prisma.IntFilter<"orders"> | number
  customerId?: Prisma.IntFilter<"orders"> | number
  staffId?: Prisma.IntFilter<"orders"> | number
  status?: Prisma.StringFilter<"orders"> | string
  createdAt?: Prisma.DateTimeFilter<"orders"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"orders"> | Date | string
  note?: Prisma.StringNullableFilter<"orders"> | string | null
  order_items?: Prisma.Order_itemsListRelationFilter
  customer?: Prisma.XOR<Prisma.CustomersScalarRelationFilter, Prisma.customersWhereInput>
  vehicle?: Prisma.XOR<Prisma.VehiclesScalarRelationFilter, Prisma.vehiclesWhereInput>
  staff?: Prisma.XOR<Prisma.StaffScalarRelationFilter, Prisma.staffWhereInput>
  payements?: Prisma.PaymentsListRelationFilter
}, "id">

export type ordersOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  vehicleId?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ordersCountOrderByAggregateInput
  _avg?: Prisma.ordersAvgOrderByAggregateInput
  _max?: Prisma.ordersMaxOrderByAggregateInput
  _min?: Prisma.ordersMinOrderByAggregateInput
  _sum?: Prisma.ordersSumOrderByAggregateInput
}

export type ordersScalarWhereWithAggregatesInput = {
  AND?: Prisma.ordersScalarWhereWithAggregatesInput | Prisma.ordersScalarWhereWithAggregatesInput[]
  OR?: Prisma.ordersScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ordersScalarWhereWithAggregatesInput | Prisma.ordersScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"orders"> | number
  vehicleId?: Prisma.IntWithAggregatesFilter<"orders"> | number
  customerId?: Prisma.IntWithAggregatesFilter<"orders"> | number
  staffId?: Prisma.IntWithAggregatesFilter<"orders"> | number
  status?: Prisma.StringWithAggregatesFilter<"orders"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"orders"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"orders"> | Date | string
  note?: Prisma.StringNullableWithAggregatesFilter<"orders"> | string | null
}

export type ordersCreateInput = {
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  note?: string | null
  order_items?: Prisma.order_itemsCreateNestedManyWithoutOrderInput
  customer: Prisma.customersCreateNestedOneWithoutOrdersInput
  vehicle: Prisma.vehiclesCreateNestedOneWithoutOrdersInput
  staff: Prisma.staffCreateNestedOneWithoutOrdersInput
  payements?: Prisma.paymentsCreateNestedManyWithoutOrderInput
}

export type ordersUncheckedCreateInput = {
  id?: number
  vehicleId: number
  customerId: number
  staffId: number
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  note?: string | null
  order_items?: Prisma.order_itemsUncheckedCreateNestedManyWithoutOrderInput
  payements?: Prisma.paymentsUncheckedCreateNestedManyWithoutOrderInput
}

export type ordersUpdateInput = {
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order_items?: Prisma.order_itemsUpdateManyWithoutOrderNestedInput
  customer?: Prisma.customersUpdateOneRequiredWithoutOrdersNestedInput
  vehicle?: Prisma.vehiclesUpdateOneRequiredWithoutOrdersNestedInput
  staff?: Prisma.staffUpdateOneRequiredWithoutOrdersNestedInput
  payements?: Prisma.paymentsUpdateManyWithoutOrderNestedInput
}

export type ordersUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  vehicleId?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.IntFieldUpdateOperationsInput | number
  staffId?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order_items?: Prisma.order_itemsUncheckedUpdateManyWithoutOrderNestedInput
  payements?: Prisma.paymentsUncheckedUpdateManyWithoutOrderNestedInput
}

export type ordersCreateManyInput = {
  id?: number
  vehicleId: number
  customerId: number
  staffId: number
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  note?: string | null
}

export type ordersUpdateManyMutationInput = {
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ordersUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  vehicleId?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.IntFieldUpdateOperationsInput | number
  staffId?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type OrdersListRelationFilter = {
  every?: Prisma.ordersWhereInput
  some?: Prisma.ordersWhereInput
  none?: Prisma.ordersWhereInput
}

export type ordersOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ordersCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  vehicleId?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  note?: Prisma.SortOrder
}

export type ordersAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  vehicleId?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
}

export type ordersMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  vehicleId?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  note?: Prisma.SortOrder
}

export type ordersMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  vehicleId?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  note?: Prisma.SortOrder
}

export type ordersSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  vehicleId?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
}

export type OrdersScalarRelationFilter = {
  is?: Prisma.ordersWhereInput
  isNot?: Prisma.ordersWhereInput
}

export type ordersCreateNestedManyWithoutVehicleInput = {
  create?: Prisma.XOR<Prisma.ordersCreateWithoutVehicleInput, Prisma.ordersUncheckedCreateWithoutVehicleInput> | Prisma.ordersCreateWithoutVehicleInput[] | Prisma.ordersUncheckedCreateWithoutVehicleInput[]
  connectOrCreate?: Prisma.ordersCreateOrConnectWithoutVehicleInput | Prisma.ordersCreateOrConnectWithoutVehicleInput[]
  createMany?: Prisma.ordersCreateManyVehicleInputEnvelope
  connect?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
}

export type ordersUncheckedCreateNestedManyWithoutVehicleInput = {
  create?: Prisma.XOR<Prisma.ordersCreateWithoutVehicleInput, Prisma.ordersUncheckedCreateWithoutVehicleInput> | Prisma.ordersCreateWithoutVehicleInput[] | Prisma.ordersUncheckedCreateWithoutVehicleInput[]
  connectOrCreate?: Prisma.ordersCreateOrConnectWithoutVehicleInput | Prisma.ordersCreateOrConnectWithoutVehicleInput[]
  createMany?: Prisma.ordersCreateManyVehicleInputEnvelope
  connect?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
}

export type ordersUpdateManyWithoutVehicleNestedInput = {
  create?: Prisma.XOR<Prisma.ordersCreateWithoutVehicleInput, Prisma.ordersUncheckedCreateWithoutVehicleInput> | Prisma.ordersCreateWithoutVehicleInput[] | Prisma.ordersUncheckedCreateWithoutVehicleInput[]
  connectOrCreate?: Prisma.ordersCreateOrConnectWithoutVehicleInput | Prisma.ordersCreateOrConnectWithoutVehicleInput[]
  upsert?: Prisma.ordersUpsertWithWhereUniqueWithoutVehicleInput | Prisma.ordersUpsertWithWhereUniqueWithoutVehicleInput[]
  createMany?: Prisma.ordersCreateManyVehicleInputEnvelope
  set?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  disconnect?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  delete?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  connect?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  update?: Prisma.ordersUpdateWithWhereUniqueWithoutVehicleInput | Prisma.ordersUpdateWithWhereUniqueWithoutVehicleInput[]
  updateMany?: Prisma.ordersUpdateManyWithWhereWithoutVehicleInput | Prisma.ordersUpdateManyWithWhereWithoutVehicleInput[]
  deleteMany?: Prisma.ordersScalarWhereInput | Prisma.ordersScalarWhereInput[]
}

export type ordersUncheckedUpdateManyWithoutVehicleNestedInput = {
  create?: Prisma.XOR<Prisma.ordersCreateWithoutVehicleInput, Prisma.ordersUncheckedCreateWithoutVehicleInput> | Prisma.ordersCreateWithoutVehicleInput[] | Prisma.ordersUncheckedCreateWithoutVehicleInput[]
  connectOrCreate?: Prisma.ordersCreateOrConnectWithoutVehicleInput | Prisma.ordersCreateOrConnectWithoutVehicleInput[]
  upsert?: Prisma.ordersUpsertWithWhereUniqueWithoutVehicleInput | Prisma.ordersUpsertWithWhereUniqueWithoutVehicleInput[]
  createMany?: Prisma.ordersCreateManyVehicleInputEnvelope
  set?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  disconnect?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  delete?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  connect?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  update?: Prisma.ordersUpdateWithWhereUniqueWithoutVehicleInput | Prisma.ordersUpdateWithWhereUniqueWithoutVehicleInput[]
  updateMany?: Prisma.ordersUpdateManyWithWhereWithoutVehicleInput | Prisma.ordersUpdateManyWithWhereWithoutVehicleInput[]
  deleteMany?: Prisma.ordersScalarWhereInput | Prisma.ordersScalarWhereInput[]
}

export type ordersCreateNestedManyWithoutStaffInput = {
  create?: Prisma.XOR<Prisma.ordersCreateWithoutStaffInput, Prisma.ordersUncheckedCreateWithoutStaffInput> | Prisma.ordersCreateWithoutStaffInput[] | Prisma.ordersUncheckedCreateWithoutStaffInput[]
  connectOrCreate?: Prisma.ordersCreateOrConnectWithoutStaffInput | Prisma.ordersCreateOrConnectWithoutStaffInput[]
  createMany?: Prisma.ordersCreateManyStaffInputEnvelope
  connect?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
}

export type ordersUncheckedCreateNestedManyWithoutStaffInput = {
  create?: Prisma.XOR<Prisma.ordersCreateWithoutStaffInput, Prisma.ordersUncheckedCreateWithoutStaffInput> | Prisma.ordersCreateWithoutStaffInput[] | Prisma.ordersUncheckedCreateWithoutStaffInput[]
  connectOrCreate?: Prisma.ordersCreateOrConnectWithoutStaffInput | Prisma.ordersCreateOrConnectWithoutStaffInput[]
  createMany?: Prisma.ordersCreateManyStaffInputEnvelope
  connect?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
}

export type ordersUpdateManyWithoutStaffNestedInput = {
  create?: Prisma.XOR<Prisma.ordersCreateWithoutStaffInput, Prisma.ordersUncheckedCreateWithoutStaffInput> | Prisma.ordersCreateWithoutStaffInput[] | Prisma.ordersUncheckedCreateWithoutStaffInput[]
  connectOrCreate?: Prisma.ordersCreateOrConnectWithoutStaffInput | Prisma.ordersCreateOrConnectWithoutStaffInput[]
  upsert?: Prisma.ordersUpsertWithWhereUniqueWithoutStaffInput | Prisma.ordersUpsertWithWhereUniqueWithoutStaffInput[]
  createMany?: Prisma.ordersCreateManyStaffInputEnvelope
  set?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  disconnect?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  delete?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  connect?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  update?: Prisma.ordersUpdateWithWhereUniqueWithoutStaffInput | Prisma.ordersUpdateWithWhereUniqueWithoutStaffInput[]
  updateMany?: Prisma.ordersUpdateManyWithWhereWithoutStaffInput | Prisma.ordersUpdateManyWithWhereWithoutStaffInput[]
  deleteMany?: Prisma.ordersScalarWhereInput | Prisma.ordersScalarWhereInput[]
}

export type ordersUncheckedUpdateManyWithoutStaffNestedInput = {
  create?: Prisma.XOR<Prisma.ordersCreateWithoutStaffInput, Prisma.ordersUncheckedCreateWithoutStaffInput> | Prisma.ordersCreateWithoutStaffInput[] | Prisma.ordersUncheckedCreateWithoutStaffInput[]
  connectOrCreate?: Prisma.ordersCreateOrConnectWithoutStaffInput | Prisma.ordersCreateOrConnectWithoutStaffInput[]
  upsert?: Prisma.ordersUpsertWithWhereUniqueWithoutStaffInput | Prisma.ordersUpsertWithWhereUniqueWithoutStaffInput[]
  createMany?: Prisma.ordersCreateManyStaffInputEnvelope
  set?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  disconnect?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  delete?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  connect?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  update?: Prisma.ordersUpdateWithWhereUniqueWithoutStaffInput | Prisma.ordersUpdateWithWhereUniqueWithoutStaffInput[]
  updateMany?: Prisma.ordersUpdateManyWithWhereWithoutStaffInput | Prisma.ordersUpdateManyWithWhereWithoutStaffInput[]
  deleteMany?: Prisma.ordersScalarWhereInput | Prisma.ordersScalarWhereInput[]
}

export type ordersCreateNestedManyWithoutCustomerInput = {
  create?: Prisma.XOR<Prisma.ordersCreateWithoutCustomerInput, Prisma.ordersUncheckedCreateWithoutCustomerInput> | Prisma.ordersCreateWithoutCustomerInput[] | Prisma.ordersUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.ordersCreateOrConnectWithoutCustomerInput | Prisma.ordersCreateOrConnectWithoutCustomerInput[]
  createMany?: Prisma.ordersCreateManyCustomerInputEnvelope
  connect?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
}

export type ordersUncheckedCreateNestedManyWithoutCustomerInput = {
  create?: Prisma.XOR<Prisma.ordersCreateWithoutCustomerInput, Prisma.ordersUncheckedCreateWithoutCustomerInput> | Prisma.ordersCreateWithoutCustomerInput[] | Prisma.ordersUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.ordersCreateOrConnectWithoutCustomerInput | Prisma.ordersCreateOrConnectWithoutCustomerInput[]
  createMany?: Prisma.ordersCreateManyCustomerInputEnvelope
  connect?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
}

export type ordersUpdateManyWithoutCustomerNestedInput = {
  create?: Prisma.XOR<Prisma.ordersCreateWithoutCustomerInput, Prisma.ordersUncheckedCreateWithoutCustomerInput> | Prisma.ordersCreateWithoutCustomerInput[] | Prisma.ordersUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.ordersCreateOrConnectWithoutCustomerInput | Prisma.ordersCreateOrConnectWithoutCustomerInput[]
  upsert?: Prisma.ordersUpsertWithWhereUniqueWithoutCustomerInput | Prisma.ordersUpsertWithWhereUniqueWithoutCustomerInput[]
  createMany?: Prisma.ordersCreateManyCustomerInputEnvelope
  set?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  disconnect?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  delete?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  connect?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  update?: Prisma.ordersUpdateWithWhereUniqueWithoutCustomerInput | Prisma.ordersUpdateWithWhereUniqueWithoutCustomerInput[]
  updateMany?: Prisma.ordersUpdateManyWithWhereWithoutCustomerInput | Prisma.ordersUpdateManyWithWhereWithoutCustomerInput[]
  deleteMany?: Prisma.ordersScalarWhereInput | Prisma.ordersScalarWhereInput[]
}

export type ordersUncheckedUpdateManyWithoutCustomerNestedInput = {
  create?: Prisma.XOR<Prisma.ordersCreateWithoutCustomerInput, Prisma.ordersUncheckedCreateWithoutCustomerInput> | Prisma.ordersCreateWithoutCustomerInput[] | Prisma.ordersUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.ordersCreateOrConnectWithoutCustomerInput | Prisma.ordersCreateOrConnectWithoutCustomerInput[]
  upsert?: Prisma.ordersUpsertWithWhereUniqueWithoutCustomerInput | Prisma.ordersUpsertWithWhereUniqueWithoutCustomerInput[]
  createMany?: Prisma.ordersCreateManyCustomerInputEnvelope
  set?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  disconnect?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  delete?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  connect?: Prisma.ordersWhereUniqueInput | Prisma.ordersWhereUniqueInput[]
  update?: Prisma.ordersUpdateWithWhereUniqueWithoutCustomerInput | Prisma.ordersUpdateWithWhereUniqueWithoutCustomerInput[]
  updateMany?: Prisma.ordersUpdateManyWithWhereWithoutCustomerInput | Prisma.ordersUpdateManyWithWhereWithoutCustomerInput[]
  deleteMany?: Prisma.ordersScalarWhereInput | Prisma.ordersScalarWhereInput[]
}

export type ordersCreateNestedOneWithoutPayementsInput = {
  create?: Prisma.XOR<Prisma.ordersCreateWithoutPayementsInput, Prisma.ordersUncheckedCreateWithoutPayementsInput>
  connectOrCreate?: Prisma.ordersCreateOrConnectWithoutPayementsInput
  connect?: Prisma.ordersWhereUniqueInput
}

export type ordersUpdateOneRequiredWithoutPayementsNestedInput = {
  create?: Prisma.XOR<Prisma.ordersCreateWithoutPayementsInput, Prisma.ordersUncheckedCreateWithoutPayementsInput>
  connectOrCreate?: Prisma.ordersCreateOrConnectWithoutPayementsInput
  upsert?: Prisma.ordersUpsertWithoutPayementsInput
  connect?: Prisma.ordersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ordersUpdateToOneWithWhereWithoutPayementsInput, Prisma.ordersUpdateWithoutPayementsInput>, Prisma.ordersUncheckedUpdateWithoutPayementsInput>
}

export type ordersCreateNestedOneWithoutOrder_itemsInput = {
  create?: Prisma.XOR<Prisma.ordersCreateWithoutOrder_itemsInput, Prisma.ordersUncheckedCreateWithoutOrder_itemsInput>
  connectOrCreate?: Prisma.ordersCreateOrConnectWithoutOrder_itemsInput
  connect?: Prisma.ordersWhereUniqueInput
}

export type ordersUpdateOneRequiredWithoutOrder_itemsNestedInput = {
  create?: Prisma.XOR<Prisma.ordersCreateWithoutOrder_itemsInput, Prisma.ordersUncheckedCreateWithoutOrder_itemsInput>
  connectOrCreate?: Prisma.ordersCreateOrConnectWithoutOrder_itemsInput
  upsert?: Prisma.ordersUpsertWithoutOrder_itemsInput
  connect?: Prisma.ordersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ordersUpdateToOneWithWhereWithoutOrder_itemsInput, Prisma.ordersUpdateWithoutOrder_itemsInput>, Prisma.ordersUncheckedUpdateWithoutOrder_itemsInput>
}

export type ordersCreateWithoutVehicleInput = {
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  note?: string | null
  order_items?: Prisma.order_itemsCreateNestedManyWithoutOrderInput
  customer: Prisma.customersCreateNestedOneWithoutOrdersInput
  staff: Prisma.staffCreateNestedOneWithoutOrdersInput
  payements?: Prisma.paymentsCreateNestedManyWithoutOrderInput
}

export type ordersUncheckedCreateWithoutVehicleInput = {
  id?: number
  customerId: number
  staffId: number
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  note?: string | null
  order_items?: Prisma.order_itemsUncheckedCreateNestedManyWithoutOrderInput
  payements?: Prisma.paymentsUncheckedCreateNestedManyWithoutOrderInput
}

export type ordersCreateOrConnectWithoutVehicleInput = {
  where: Prisma.ordersWhereUniqueInput
  create: Prisma.XOR<Prisma.ordersCreateWithoutVehicleInput, Prisma.ordersUncheckedCreateWithoutVehicleInput>
}

export type ordersCreateManyVehicleInputEnvelope = {
  data: Prisma.ordersCreateManyVehicleInput | Prisma.ordersCreateManyVehicleInput[]
  skipDuplicates?: boolean
}

export type ordersUpsertWithWhereUniqueWithoutVehicleInput = {
  where: Prisma.ordersWhereUniqueInput
  update: Prisma.XOR<Prisma.ordersUpdateWithoutVehicleInput, Prisma.ordersUncheckedUpdateWithoutVehicleInput>
  create: Prisma.XOR<Prisma.ordersCreateWithoutVehicleInput, Prisma.ordersUncheckedCreateWithoutVehicleInput>
}

export type ordersUpdateWithWhereUniqueWithoutVehicleInput = {
  where: Prisma.ordersWhereUniqueInput
  data: Prisma.XOR<Prisma.ordersUpdateWithoutVehicleInput, Prisma.ordersUncheckedUpdateWithoutVehicleInput>
}

export type ordersUpdateManyWithWhereWithoutVehicleInput = {
  where: Prisma.ordersScalarWhereInput
  data: Prisma.XOR<Prisma.ordersUpdateManyMutationInput, Prisma.ordersUncheckedUpdateManyWithoutVehicleInput>
}

export type ordersScalarWhereInput = {
  AND?: Prisma.ordersScalarWhereInput | Prisma.ordersScalarWhereInput[]
  OR?: Prisma.ordersScalarWhereInput[]
  NOT?: Prisma.ordersScalarWhereInput | Prisma.ordersScalarWhereInput[]
  id?: Prisma.IntFilter<"orders"> | number
  vehicleId?: Prisma.IntFilter<"orders"> | number
  customerId?: Prisma.IntFilter<"orders"> | number
  staffId?: Prisma.IntFilter<"orders"> | number
  status?: Prisma.StringFilter<"orders"> | string
  createdAt?: Prisma.DateTimeFilter<"orders"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"orders"> | Date | string
  note?: Prisma.StringNullableFilter<"orders"> | string | null
}

export type ordersCreateWithoutStaffInput = {
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  note?: string | null
  order_items?: Prisma.order_itemsCreateNestedManyWithoutOrderInput
  customer: Prisma.customersCreateNestedOneWithoutOrdersInput
  vehicle: Prisma.vehiclesCreateNestedOneWithoutOrdersInput
  payements?: Prisma.paymentsCreateNestedManyWithoutOrderInput
}

export type ordersUncheckedCreateWithoutStaffInput = {
  id?: number
  vehicleId: number
  customerId: number
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  note?: string | null
  order_items?: Prisma.order_itemsUncheckedCreateNestedManyWithoutOrderInput
  payements?: Prisma.paymentsUncheckedCreateNestedManyWithoutOrderInput
}

export type ordersCreateOrConnectWithoutStaffInput = {
  where: Prisma.ordersWhereUniqueInput
  create: Prisma.XOR<Prisma.ordersCreateWithoutStaffInput, Prisma.ordersUncheckedCreateWithoutStaffInput>
}

export type ordersCreateManyStaffInputEnvelope = {
  data: Prisma.ordersCreateManyStaffInput | Prisma.ordersCreateManyStaffInput[]
  skipDuplicates?: boolean
}

export type ordersUpsertWithWhereUniqueWithoutStaffInput = {
  where: Prisma.ordersWhereUniqueInput
  update: Prisma.XOR<Prisma.ordersUpdateWithoutStaffInput, Prisma.ordersUncheckedUpdateWithoutStaffInput>
  create: Prisma.XOR<Prisma.ordersCreateWithoutStaffInput, Prisma.ordersUncheckedCreateWithoutStaffInput>
}

export type ordersUpdateWithWhereUniqueWithoutStaffInput = {
  where: Prisma.ordersWhereUniqueInput
  data: Prisma.XOR<Prisma.ordersUpdateWithoutStaffInput, Prisma.ordersUncheckedUpdateWithoutStaffInput>
}

export type ordersUpdateManyWithWhereWithoutStaffInput = {
  where: Prisma.ordersScalarWhereInput
  data: Prisma.XOR<Prisma.ordersUpdateManyMutationInput, Prisma.ordersUncheckedUpdateManyWithoutStaffInput>
}

export type ordersCreateWithoutCustomerInput = {
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  note?: string | null
  order_items?: Prisma.order_itemsCreateNestedManyWithoutOrderInput
  vehicle: Prisma.vehiclesCreateNestedOneWithoutOrdersInput
  staff: Prisma.staffCreateNestedOneWithoutOrdersInput
  payements?: Prisma.paymentsCreateNestedManyWithoutOrderInput
}

export type ordersUncheckedCreateWithoutCustomerInput = {
  id?: number
  vehicleId: number
  staffId: number
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  note?: string | null
  order_items?: Prisma.order_itemsUncheckedCreateNestedManyWithoutOrderInput
  payements?: Prisma.paymentsUncheckedCreateNestedManyWithoutOrderInput
}

export type ordersCreateOrConnectWithoutCustomerInput = {
  where: Prisma.ordersWhereUniqueInput
  create: Prisma.XOR<Prisma.ordersCreateWithoutCustomerInput, Prisma.ordersUncheckedCreateWithoutCustomerInput>
}

export type ordersCreateManyCustomerInputEnvelope = {
  data: Prisma.ordersCreateManyCustomerInput | Prisma.ordersCreateManyCustomerInput[]
  skipDuplicates?: boolean
}

export type ordersUpsertWithWhereUniqueWithoutCustomerInput = {
  where: Prisma.ordersWhereUniqueInput
  update: Prisma.XOR<Prisma.ordersUpdateWithoutCustomerInput, Prisma.ordersUncheckedUpdateWithoutCustomerInput>
  create: Prisma.XOR<Prisma.ordersCreateWithoutCustomerInput, Prisma.ordersUncheckedCreateWithoutCustomerInput>
}

export type ordersUpdateWithWhereUniqueWithoutCustomerInput = {
  where: Prisma.ordersWhereUniqueInput
  data: Prisma.XOR<Prisma.ordersUpdateWithoutCustomerInput, Prisma.ordersUncheckedUpdateWithoutCustomerInput>
}

export type ordersUpdateManyWithWhereWithoutCustomerInput = {
  where: Prisma.ordersScalarWhereInput
  data: Prisma.XOR<Prisma.ordersUpdateManyMutationInput, Prisma.ordersUncheckedUpdateManyWithoutCustomerInput>
}

export type ordersCreateWithoutPayementsInput = {
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  note?: string | null
  order_items?: Prisma.order_itemsCreateNestedManyWithoutOrderInput
  customer: Prisma.customersCreateNestedOneWithoutOrdersInput
  vehicle: Prisma.vehiclesCreateNestedOneWithoutOrdersInput
  staff: Prisma.staffCreateNestedOneWithoutOrdersInput
}

export type ordersUncheckedCreateWithoutPayementsInput = {
  id?: number
  vehicleId: number
  customerId: number
  staffId: number
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  note?: string | null
  order_items?: Prisma.order_itemsUncheckedCreateNestedManyWithoutOrderInput
}

export type ordersCreateOrConnectWithoutPayementsInput = {
  where: Prisma.ordersWhereUniqueInput
  create: Prisma.XOR<Prisma.ordersCreateWithoutPayementsInput, Prisma.ordersUncheckedCreateWithoutPayementsInput>
}

export type ordersUpsertWithoutPayementsInput = {
  update: Prisma.XOR<Prisma.ordersUpdateWithoutPayementsInput, Prisma.ordersUncheckedUpdateWithoutPayementsInput>
  create: Prisma.XOR<Prisma.ordersCreateWithoutPayementsInput, Prisma.ordersUncheckedCreateWithoutPayementsInput>
  where?: Prisma.ordersWhereInput
}

export type ordersUpdateToOneWithWhereWithoutPayementsInput = {
  where?: Prisma.ordersWhereInput
  data: Prisma.XOR<Prisma.ordersUpdateWithoutPayementsInput, Prisma.ordersUncheckedUpdateWithoutPayementsInput>
}

export type ordersUpdateWithoutPayementsInput = {
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order_items?: Prisma.order_itemsUpdateManyWithoutOrderNestedInput
  customer?: Prisma.customersUpdateOneRequiredWithoutOrdersNestedInput
  vehicle?: Prisma.vehiclesUpdateOneRequiredWithoutOrdersNestedInput
  staff?: Prisma.staffUpdateOneRequiredWithoutOrdersNestedInput
}

export type ordersUncheckedUpdateWithoutPayementsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  vehicleId?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.IntFieldUpdateOperationsInput | number
  staffId?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order_items?: Prisma.order_itemsUncheckedUpdateManyWithoutOrderNestedInput
}

export type ordersCreateWithoutOrder_itemsInput = {
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  note?: string | null
  customer: Prisma.customersCreateNestedOneWithoutOrdersInput
  vehicle: Prisma.vehiclesCreateNestedOneWithoutOrdersInput
  staff: Prisma.staffCreateNestedOneWithoutOrdersInput
  payements?: Prisma.paymentsCreateNestedManyWithoutOrderInput
}

export type ordersUncheckedCreateWithoutOrder_itemsInput = {
  id?: number
  vehicleId: number
  customerId: number
  staffId: number
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  note?: string | null
  payements?: Prisma.paymentsUncheckedCreateNestedManyWithoutOrderInput
}

export type ordersCreateOrConnectWithoutOrder_itemsInput = {
  where: Prisma.ordersWhereUniqueInput
  create: Prisma.XOR<Prisma.ordersCreateWithoutOrder_itemsInput, Prisma.ordersUncheckedCreateWithoutOrder_itemsInput>
}

export type ordersUpsertWithoutOrder_itemsInput = {
  update: Prisma.XOR<Prisma.ordersUpdateWithoutOrder_itemsInput, Prisma.ordersUncheckedUpdateWithoutOrder_itemsInput>
  create: Prisma.XOR<Prisma.ordersCreateWithoutOrder_itemsInput, Prisma.ordersUncheckedCreateWithoutOrder_itemsInput>
  where?: Prisma.ordersWhereInput
}

export type ordersUpdateToOneWithWhereWithoutOrder_itemsInput = {
  where?: Prisma.ordersWhereInput
  data: Prisma.XOR<Prisma.ordersUpdateWithoutOrder_itemsInput, Prisma.ordersUncheckedUpdateWithoutOrder_itemsInput>
}

export type ordersUpdateWithoutOrder_itemsInput = {
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customer?: Prisma.customersUpdateOneRequiredWithoutOrdersNestedInput
  vehicle?: Prisma.vehiclesUpdateOneRequiredWithoutOrdersNestedInput
  staff?: Prisma.staffUpdateOneRequiredWithoutOrdersNestedInput
  payements?: Prisma.paymentsUpdateManyWithoutOrderNestedInput
}

export type ordersUncheckedUpdateWithoutOrder_itemsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  vehicleId?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.IntFieldUpdateOperationsInput | number
  staffId?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payements?: Prisma.paymentsUncheckedUpdateManyWithoutOrderNestedInput
}

export type ordersCreateManyVehicleInput = {
  id?: number
  customerId: number
  staffId: number
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  note?: string | null
}

export type ordersUpdateWithoutVehicleInput = {
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order_items?: Prisma.order_itemsUpdateManyWithoutOrderNestedInput
  customer?: Prisma.customersUpdateOneRequiredWithoutOrdersNestedInput
  staff?: Prisma.staffUpdateOneRequiredWithoutOrdersNestedInput
  payements?: Prisma.paymentsUpdateManyWithoutOrderNestedInput
}

export type ordersUncheckedUpdateWithoutVehicleInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.IntFieldUpdateOperationsInput | number
  staffId?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order_items?: Prisma.order_itemsUncheckedUpdateManyWithoutOrderNestedInput
  payements?: Prisma.paymentsUncheckedUpdateManyWithoutOrderNestedInput
}

export type ordersUncheckedUpdateManyWithoutVehicleInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.IntFieldUpdateOperationsInput | number
  staffId?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ordersCreateManyStaffInput = {
  id?: number
  vehicleId: number
  customerId: number
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  note?: string | null
}

export type ordersUpdateWithoutStaffInput = {
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order_items?: Prisma.order_itemsUpdateManyWithoutOrderNestedInput
  customer?: Prisma.customersUpdateOneRequiredWithoutOrdersNestedInput
  vehicle?: Prisma.vehiclesUpdateOneRequiredWithoutOrdersNestedInput
  payements?: Prisma.paymentsUpdateManyWithoutOrderNestedInput
}

export type ordersUncheckedUpdateWithoutStaffInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  vehicleId?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order_items?: Prisma.order_itemsUncheckedUpdateManyWithoutOrderNestedInput
  payements?: Prisma.paymentsUncheckedUpdateManyWithoutOrderNestedInput
}

export type ordersUncheckedUpdateManyWithoutStaffInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  vehicleId?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ordersCreateManyCustomerInput = {
  id?: number
  vehicleId: number
  staffId: number
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  note?: string | null
}

export type ordersUpdateWithoutCustomerInput = {
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order_items?: Prisma.order_itemsUpdateManyWithoutOrderNestedInput
  vehicle?: Prisma.vehiclesUpdateOneRequiredWithoutOrdersNestedInput
  staff?: Prisma.staffUpdateOneRequiredWithoutOrdersNestedInput
  payements?: Prisma.paymentsUpdateManyWithoutOrderNestedInput
}

export type ordersUncheckedUpdateWithoutCustomerInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  vehicleId?: Prisma.IntFieldUpdateOperationsInput | number
  staffId?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order_items?: Prisma.order_itemsUncheckedUpdateManyWithoutOrderNestedInput
  payements?: Prisma.paymentsUncheckedUpdateManyWithoutOrderNestedInput
}

export type ordersUncheckedUpdateManyWithoutCustomerInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  vehicleId?: Prisma.IntFieldUpdateOperationsInput | number
  staffId?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type OrdersCountOutputType
 */

export type OrdersCountOutputType = {
  order_items: number
  payements: number
}

export type OrdersCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order_items?: boolean | OrdersCountOutputTypeCountOrder_itemsArgs
  payements?: boolean | OrdersCountOutputTypeCountPayementsArgs
}

/**
 * OrdersCountOutputType without action
 */
export type OrdersCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrdersCountOutputType
   */
  select?: Prisma.OrdersCountOutputTypeSelect<ExtArgs> | null
}

/**
 * OrdersCountOutputType without action
 */
export type OrdersCountOutputTypeCountOrder_itemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.order_itemsWhereInput
}

/**
 * OrdersCountOutputType without action
 */
export type OrdersCountOutputTypeCountPayementsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.paymentsWhereInput
}


export type ordersSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  vehicleId?: boolean
  customerId?: boolean
  staffId?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  note?: boolean
  order_items?: boolean | Prisma.orders$order_itemsArgs<ExtArgs>
  customer?: boolean | Prisma.customersDefaultArgs<ExtArgs>
  vehicle?: boolean | Prisma.vehiclesDefaultArgs<ExtArgs>
  staff?: boolean | Prisma.staffDefaultArgs<ExtArgs>
  payements?: boolean | Prisma.orders$payementsArgs<ExtArgs>
  _count?: boolean | Prisma.OrdersCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["orders"]>

export type ordersSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  vehicleId?: boolean
  customerId?: boolean
  staffId?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  note?: boolean
  customer?: boolean | Prisma.customersDefaultArgs<ExtArgs>
  vehicle?: boolean | Prisma.vehiclesDefaultArgs<ExtArgs>
  staff?: boolean | Prisma.staffDefaultArgs<ExtArgs>
}, ExtArgs["result"]["orders"]>

export type ordersSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  vehicleId?: boolean
  customerId?: boolean
  staffId?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  note?: boolean
  customer?: boolean | Prisma.customersDefaultArgs<ExtArgs>
  vehicle?: boolean | Prisma.vehiclesDefaultArgs<ExtArgs>
  staff?: boolean | Prisma.staffDefaultArgs<ExtArgs>
}, ExtArgs["result"]["orders"]>

export type ordersSelectScalar = {
  id?: boolean
  vehicleId?: boolean
  customerId?: boolean
  staffId?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  note?: boolean
}

export type ordersOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "vehicleId" | "customerId" | "staffId" | "status" | "createdAt" | "updatedAt" | "note", ExtArgs["result"]["orders"]>
export type ordersInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order_items?: boolean | Prisma.orders$order_itemsArgs<ExtArgs>
  customer?: boolean | Prisma.customersDefaultArgs<ExtArgs>
  vehicle?: boolean | Prisma.vehiclesDefaultArgs<ExtArgs>
  staff?: boolean | Prisma.staffDefaultArgs<ExtArgs>
  payements?: boolean | Prisma.orders$payementsArgs<ExtArgs>
  _count?: boolean | Prisma.OrdersCountOutputTypeDefaultArgs<ExtArgs>
}
export type ordersIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customer?: boolean | Prisma.customersDefaultArgs<ExtArgs>
  vehicle?: boolean | Prisma.vehiclesDefaultArgs<ExtArgs>
  staff?: boolean | Prisma.staffDefaultArgs<ExtArgs>
}
export type ordersIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customer?: boolean | Prisma.customersDefaultArgs<ExtArgs>
  vehicle?: boolean | Prisma.vehiclesDefaultArgs<ExtArgs>
  staff?: boolean | Prisma.staffDefaultArgs<ExtArgs>
}

export type $ordersPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "orders"
  objects: {
    order_items: Prisma.$order_itemsPayload<ExtArgs>[]
    customer: Prisma.$customersPayload<ExtArgs>
    vehicle: Prisma.$vehiclesPayload<ExtArgs>
    staff: Prisma.$staffPayload<ExtArgs>
    payements: Prisma.$paymentsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    vehicleId: number
    customerId: number
    staffId: number
    status: string
    createdAt: Date
    updatedAt: Date
    note: string | null
  }, ExtArgs["result"]["orders"]>
  composites: {}
}

export type ordersGetPayload<S extends boolean | null | undefined | ordersDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ordersPayload, S>

export type ordersCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ordersFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OrdersCountAggregateInputType | true
  }

export interface ordersDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['orders'], meta: { name: 'orders' } }
  /**
   * Find zero or one Orders that matches the filter.
   * @param {ordersFindUniqueArgs} args - Arguments to find a Orders
   * @example
   * // Get one Orders
   * const orders = await prisma.orders.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ordersFindUniqueArgs>(args: Prisma.SelectSubset<T, ordersFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ordersClient<runtime.Types.Result.GetResult<Prisma.$ordersPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Orders that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ordersFindUniqueOrThrowArgs} args - Arguments to find a Orders
   * @example
   * // Get one Orders
   * const orders = await prisma.orders.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ordersFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ordersFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ordersClient<runtime.Types.Result.GetResult<Prisma.$ordersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Orders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ordersFindFirstArgs} args - Arguments to find a Orders
   * @example
   * // Get one Orders
   * const orders = await prisma.orders.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ordersFindFirstArgs>(args?: Prisma.SelectSubset<T, ordersFindFirstArgs<ExtArgs>>): Prisma.Prisma__ordersClient<runtime.Types.Result.GetResult<Prisma.$ordersPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Orders that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ordersFindFirstOrThrowArgs} args - Arguments to find a Orders
   * @example
   * // Get one Orders
   * const orders = await prisma.orders.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ordersFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ordersFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ordersClient<runtime.Types.Result.GetResult<Prisma.$ordersPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Orders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ordersFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Orders
   * const orders = await prisma.orders.findMany()
   * 
   * // Get first 10 Orders
   * const orders = await prisma.orders.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const ordersWithIdOnly = await prisma.orders.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ordersFindManyArgs>(args?: Prisma.SelectSubset<T, ordersFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ordersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Orders.
   * @param {ordersCreateArgs} args - Arguments to create a Orders.
   * @example
   * // Create one Orders
   * const Orders = await prisma.orders.create({
   *   data: {
   *     // ... data to create a Orders
   *   }
   * })
   * 
   */
  create<T extends ordersCreateArgs>(args: Prisma.SelectSubset<T, ordersCreateArgs<ExtArgs>>): Prisma.Prisma__ordersClient<runtime.Types.Result.GetResult<Prisma.$ordersPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Orders.
   * @param {ordersCreateManyArgs} args - Arguments to create many Orders.
   * @example
   * // Create many Orders
   * const orders = await prisma.orders.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ordersCreateManyArgs>(args?: Prisma.SelectSubset<T, ordersCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Orders and returns the data saved in the database.
   * @param {ordersCreateManyAndReturnArgs} args - Arguments to create many Orders.
   * @example
   * // Create many Orders
   * const orders = await prisma.orders.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Orders and only return the `id`
   * const ordersWithIdOnly = await prisma.orders.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ordersCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ordersCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ordersPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Orders.
   * @param {ordersDeleteArgs} args - Arguments to delete one Orders.
   * @example
   * // Delete one Orders
   * const Orders = await prisma.orders.delete({
   *   where: {
   *     // ... filter to delete one Orders
   *   }
   * })
   * 
   */
  delete<T extends ordersDeleteArgs>(args: Prisma.SelectSubset<T, ordersDeleteArgs<ExtArgs>>): Prisma.Prisma__ordersClient<runtime.Types.Result.GetResult<Prisma.$ordersPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Orders.
   * @param {ordersUpdateArgs} args - Arguments to update one Orders.
   * @example
   * // Update one Orders
   * const orders = await prisma.orders.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ordersUpdateArgs>(args: Prisma.SelectSubset<T, ordersUpdateArgs<ExtArgs>>): Prisma.Prisma__ordersClient<runtime.Types.Result.GetResult<Prisma.$ordersPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Orders.
   * @param {ordersDeleteManyArgs} args - Arguments to filter Orders to delete.
   * @example
   * // Delete a few Orders
   * const { count } = await prisma.orders.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ordersDeleteManyArgs>(args?: Prisma.SelectSubset<T, ordersDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Orders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ordersUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Orders
   * const orders = await prisma.orders.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ordersUpdateManyArgs>(args: Prisma.SelectSubset<T, ordersUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Orders and returns the data updated in the database.
   * @param {ordersUpdateManyAndReturnArgs} args - Arguments to update many Orders.
   * @example
   * // Update many Orders
   * const orders = await prisma.orders.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Orders and only return the `id`
   * const ordersWithIdOnly = await prisma.orders.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ordersUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ordersUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ordersPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Orders.
   * @param {ordersUpsertArgs} args - Arguments to update or create a Orders.
   * @example
   * // Update or create a Orders
   * const orders = await prisma.orders.upsert({
   *   create: {
   *     // ... data to create a Orders
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Orders we want to update
   *   }
   * })
   */
  upsert<T extends ordersUpsertArgs>(args: Prisma.SelectSubset<T, ordersUpsertArgs<ExtArgs>>): Prisma.Prisma__ordersClient<runtime.Types.Result.GetResult<Prisma.$ordersPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Orders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ordersCountArgs} args - Arguments to filter Orders to count.
   * @example
   * // Count the number of Orders
   * const count = await prisma.orders.count({
   *   where: {
   *     // ... the filter for the Orders we want to count
   *   }
   * })
  **/
  count<T extends ordersCountArgs>(
    args?: Prisma.Subset<T, ordersCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OrdersCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Orders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrdersAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OrdersAggregateArgs>(args: Prisma.Subset<T, OrdersAggregateArgs>): Prisma.PrismaPromise<GetOrdersAggregateType<T>>

  /**
   * Group by Orders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ordersGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ordersGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ordersGroupByArgs['orderBy'] }
      : { orderBy?: ordersGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ordersGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOrdersGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the orders model
 */
readonly fields: ordersFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for orders.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ordersClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  order_items<T extends Prisma.orders$order_itemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.orders$order_itemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$order_itemsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  customer<T extends Prisma.customersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.customersDefaultArgs<ExtArgs>>): Prisma.Prisma__customersClient<runtime.Types.Result.GetResult<Prisma.$customersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  vehicle<T extends Prisma.vehiclesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.vehiclesDefaultArgs<ExtArgs>>): Prisma.Prisma__vehiclesClient<runtime.Types.Result.GetResult<Prisma.$vehiclesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  staff<T extends Prisma.staffDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.staffDefaultArgs<ExtArgs>>): Prisma.Prisma__staffClient<runtime.Types.Result.GetResult<Prisma.$staffPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  payements<T extends Prisma.orders$payementsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.orders$payementsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$paymentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the orders model
 */
export interface ordersFieldRefs {
  readonly id: Prisma.FieldRef<"orders", 'Int'>
  readonly vehicleId: Prisma.FieldRef<"orders", 'Int'>
  readonly customerId: Prisma.FieldRef<"orders", 'Int'>
  readonly staffId: Prisma.FieldRef<"orders", 'Int'>
  readonly status: Prisma.FieldRef<"orders", 'String'>
  readonly createdAt: Prisma.FieldRef<"orders", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"orders", 'DateTime'>
  readonly note: Prisma.FieldRef<"orders", 'String'>
}
    

// Custom InputTypes
/**
 * orders findUnique
 */
export type ordersFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders
   */
  select?: Prisma.ordersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders
   */
  omit?: Prisma.ordersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ordersInclude<ExtArgs> | null
  /**
   * Filter, which orders to fetch.
   */
  where: Prisma.ordersWhereUniqueInput
}

/**
 * orders findUniqueOrThrow
 */
export type ordersFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders
   */
  select?: Prisma.ordersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders
   */
  omit?: Prisma.ordersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ordersInclude<ExtArgs> | null
  /**
   * Filter, which orders to fetch.
   */
  where: Prisma.ordersWhereUniqueInput
}

/**
 * orders findFirst
 */
export type ordersFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders
   */
  select?: Prisma.ordersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders
   */
  omit?: Prisma.ordersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ordersInclude<ExtArgs> | null
  /**
   * Filter, which orders to fetch.
   */
  where?: Prisma.ordersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders to fetch.
   */
  orderBy?: Prisma.ordersOrderByWithRelationInput | Prisma.ordersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for orders.
   */
  cursor?: Prisma.ordersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orders.
   */
  distinct?: Prisma.OrdersScalarFieldEnum | Prisma.OrdersScalarFieldEnum[]
}

/**
 * orders findFirstOrThrow
 */
export type ordersFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders
   */
  select?: Prisma.ordersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders
   */
  omit?: Prisma.ordersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ordersInclude<ExtArgs> | null
  /**
   * Filter, which orders to fetch.
   */
  where?: Prisma.ordersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders to fetch.
   */
  orderBy?: Prisma.ordersOrderByWithRelationInput | Prisma.ordersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for orders.
   */
  cursor?: Prisma.ordersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orders.
   */
  distinct?: Prisma.OrdersScalarFieldEnum | Prisma.OrdersScalarFieldEnum[]
}

/**
 * orders findMany
 */
export type ordersFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders
   */
  select?: Prisma.ordersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders
   */
  omit?: Prisma.ordersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ordersInclude<ExtArgs> | null
  /**
   * Filter, which orders to fetch.
   */
  where?: Prisma.ordersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of orders to fetch.
   */
  orderBy?: Prisma.ordersOrderByWithRelationInput | Prisma.ordersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing orders.
   */
  cursor?: Prisma.ordersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` orders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` orders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of orders.
   */
  distinct?: Prisma.OrdersScalarFieldEnum | Prisma.OrdersScalarFieldEnum[]
}

/**
 * orders create
 */
export type ordersCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders
   */
  select?: Prisma.ordersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders
   */
  omit?: Prisma.ordersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ordersInclude<ExtArgs> | null
  /**
   * The data needed to create a orders.
   */
  data: Prisma.XOR<Prisma.ordersCreateInput, Prisma.ordersUncheckedCreateInput>
}

/**
 * orders createMany
 */
export type ordersCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many orders.
   */
  data: Prisma.ordersCreateManyInput | Prisma.ordersCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * orders createManyAndReturn
 */
export type ordersCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders
   */
  select?: Prisma.ordersSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the orders
   */
  omit?: Prisma.ordersOmit<ExtArgs> | null
  /**
   * The data used to create many orders.
   */
  data: Prisma.ordersCreateManyInput | Prisma.ordersCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ordersIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * orders update
 */
export type ordersUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders
   */
  select?: Prisma.ordersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders
   */
  omit?: Prisma.ordersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ordersInclude<ExtArgs> | null
  /**
   * The data needed to update a orders.
   */
  data: Prisma.XOR<Prisma.ordersUpdateInput, Prisma.ordersUncheckedUpdateInput>
  /**
   * Choose, which orders to update.
   */
  where: Prisma.ordersWhereUniqueInput
}

/**
 * orders updateMany
 */
export type ordersUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update orders.
   */
  data: Prisma.XOR<Prisma.ordersUpdateManyMutationInput, Prisma.ordersUncheckedUpdateManyInput>
  /**
   * Filter which orders to update
   */
  where?: Prisma.ordersWhereInput
  /**
   * Limit how many orders to update.
   */
  limit?: number
}

/**
 * orders updateManyAndReturn
 */
export type ordersUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders
   */
  select?: Prisma.ordersSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the orders
   */
  omit?: Prisma.ordersOmit<ExtArgs> | null
  /**
   * The data used to update orders.
   */
  data: Prisma.XOR<Prisma.ordersUpdateManyMutationInput, Prisma.ordersUncheckedUpdateManyInput>
  /**
   * Filter which orders to update
   */
  where?: Prisma.ordersWhereInput
  /**
   * Limit how many orders to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ordersIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * orders upsert
 */
export type ordersUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders
   */
  select?: Prisma.ordersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders
   */
  omit?: Prisma.ordersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ordersInclude<ExtArgs> | null
  /**
   * The filter to search for the orders to update in case it exists.
   */
  where: Prisma.ordersWhereUniqueInput
  /**
   * In case the orders found by the `where` argument doesn't exist, create a new orders with this data.
   */
  create: Prisma.XOR<Prisma.ordersCreateInput, Prisma.ordersUncheckedCreateInput>
  /**
   * In case the orders was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ordersUpdateInput, Prisma.ordersUncheckedUpdateInput>
}

/**
 * orders delete
 */
export type ordersDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders
   */
  select?: Prisma.ordersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders
   */
  omit?: Prisma.ordersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ordersInclude<ExtArgs> | null
  /**
   * Filter which orders to delete.
   */
  where: Prisma.ordersWhereUniqueInput
}

/**
 * orders deleteMany
 */
export type ordersDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which orders to delete
   */
  where?: Prisma.ordersWhereInput
  /**
   * Limit how many orders to delete.
   */
  limit?: number
}

/**
 * orders.order_items
 */
export type orders$order_itemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the order_items
   */
  select?: Prisma.order_itemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the order_items
   */
  omit?: Prisma.order_itemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.order_itemsInclude<ExtArgs> | null
  where?: Prisma.order_itemsWhereInput
  orderBy?: Prisma.order_itemsOrderByWithRelationInput | Prisma.order_itemsOrderByWithRelationInput[]
  cursor?: Prisma.order_itemsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Order_itemsScalarFieldEnum | Prisma.Order_itemsScalarFieldEnum[]
}

/**
 * orders.payements
 */
export type orders$payementsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the payments
   */
  select?: Prisma.paymentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the payments
   */
  omit?: Prisma.paymentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.paymentsInclude<ExtArgs> | null
  where?: Prisma.paymentsWhereInput
  orderBy?: Prisma.paymentsOrderByWithRelationInput | Prisma.paymentsOrderByWithRelationInput[]
  cursor?: Prisma.paymentsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PaymentsScalarFieldEnum | Prisma.PaymentsScalarFieldEnum[]
}

/**
 * orders without action
 */
export type ordersDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the orders
   */
  select?: Prisma.ordersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the orders
   */
  omit?: Prisma.ordersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ordersInclude<ExtArgs> | null
}
