
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model vehicles
 * 
 */
export type vehicles = Prisma.vehiclesModel
/**
 * Model user
 * 
 */
export type user = Prisma.userModel
/**
 * Model staff
 * 
 */
export type staff = Prisma.staffModel
/**
 * Model orders
 * 
 */
export type orders = Prisma.ordersModel
/**
 * Model customers
 * 
 */
export type customers = Prisma.customersModel
/**
 * Model payments
 * 
 */
export type payments = Prisma.paymentsModel
/**
 * Model order_items
 * 
 */
export type order_items = Prisma.order_itemsModel
/**
 * Model services
 * 
 */
export type services = Prisma.servicesModel
